//! Verification key constants — generated by scripts/extract-vk.js.
//! Replace the zero-filled placeholders below with the real values after
//! running `./scripts/compile-circuits.sh && node scripts/extract-vk.js`.

use soroban_sdk::{Env, Vec};
use crate::verifier::{G1Point, G2Point, VerifyingKey};

fn zero_g1() -> G1Point { ([0u8; 32], [0u8; 32]) }
fn zero_g2() -> G2Point { ([0u8; 32], [0u8; 32], [0u8; 32], [0u8; 32]) }

fn build_vk(env: &Env, ic_len: usize) -> VerifyingKey {
    let mut ic = Vec::new(env);
    for _ in 0..ic_len {
        ic.push_back(zero_g1());
    }
    VerifyingKey {
        alpha: zero_g1(),
        beta:  zero_g2(),
        gamma: zero_g2(),
        delta: zero_g2(),
        ic,
    }
}

/// Verification key for the deposit circuit (3 public inputs → ic length 4).
pub fn deposit_vk(env: &Env) -> VerifyingKey {
    build_vk(env, 4)
}

/// Verification key for the transfer circuit (4 public inputs → ic length 5).
pub fn transfer_vk(env: &Env) -> VerifyingKey {
    build_vk(env, 5)
}

/// Verification key for the withdraw circuit (5 public inputs → ic length 6).
pub fn withdraw_vk(env: &Env) -> VerifyingKey {
    build_vk(env, 6)
}
