#!/usr/bin/env node
// scripts/extract-vk.js
// Read build/{circuit}/verification_key.json for each circuit and emit
// contracts/shield_pool/src/vk_constants.rs with real G1/G2 point bytes.
"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT      = path.resolve(__dirname, "..");
const BUILD_DIR = path.join(ROOT, "build");
const OUT_FILE  = path.join(ROOT, "contracts", "shield_pool", "src", "vk_constants.rs");

const CIRCUITS = ["deposit", "transfer", "withdraw"];

// ── Helpers ──────────────────────────────────────────────────────────────────

/** BigInt string from VK JSON → 32-byte big-endian Rust array literal. */
function fieldToRustBytes(decStr) {
  const hex = BigInt(decStr).toString(16).padStart(64, "0");
  const bytes = [];
  for (let i = 0; i < 64; i += 2) bytes.push(`0x${hex.slice(i, i + 2)}`);
  return `[${bytes.join(", ")}]`;
}

/** snarkjs VK G1 point: [x_dec, y_dec, "1"] */
function g1(pt) {
  return `(${fieldToRustBytes(pt[0])}, ${fieldToRustBytes(pt[1])})`;
}

/**
 * snarkjs VK G2 point: [[x0,x1],[y0,y1],"1"]  (coefficients in Fp2)
 * Soroban verifier expects (x1, x0, y1, y0) — i.e. each Fp2 pair is
 * stored as (high_coeff, low_coeff) matching the BN254 G2 affine convention.
 */
function g2(pt) {
  return `(${fieldToRustBytes(pt[0][1])}, ${fieldToRustBytes(pt[0][0])}, ${fieldToRustBytes(pt[1][1])}, ${fieldToRustBytes(pt[1][0])})`;
}

/** Render the ic Vec entries for a circuit's VK. */
function icEntries(ic) {
  return ic.map((pt) => `        ic.push_back(${g1(pt)});`).join("\n");
}

// ── Load VKs ─────────────────────────────────────────────────────────────────

const vks = {};
for (const name of CIRCUITS) {
  const vkPath = path.join(BUILD_DIR, name, "verification_key.json");
  if (!fs.existsSync(vkPath)) {
    console.error(`ERROR: ${vkPath} not found. Run compile-circuits.sh first.`);
    process.exit(1);
  }
  vks[name] = JSON.parse(fs.readFileSync(vkPath, "utf8"));
  console.log(`[${name}] loaded VK  (${vks[name].IC.length} IC points)`);
}

// ── Emit Rust ─────────────────────────────────────────────────────────────────

const rust = `//! vk_constants.rs — generated by scripts/extract-vk.js. DO NOT EDIT.
//! Re-generate with: ./scripts/compile-circuits.sh

use soroban_sdk::{Env, Vec};
use crate::verifier::{G1Point, G2Point, VerifyingKey};

${CIRCUITS.map((name) => {
  const vk = vks[name];
  const fnName = `${name}_vk`;
  return `/// Verification key for the ${name} circuit (${vk.IC.length - 1} public inputs).
pub fn ${fnName}(env: &Env) -> VerifyingKey {
    let mut ic: Vec<G1Point> = Vec::new(env);
${icEntries(vk.IC)}
    VerifyingKey {
        alpha: ${g1(vk.vk_alpha_1)},
        beta:  ${g2(vk.vk_beta_2)},
        gamma: ${g2(vk.vk_gamma_2)},
        delta: ${g2(vk.vk_delta_2)},
        ic,
    }
}`;
}).join("\n\n")}
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, rust, "utf8");
console.log(`\nWrote ${OUT_FILE}`);
